# Generated by Django 5.2 on 2025-05-18 01:13

import companies.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', companies.encryption.EncryptedCharField(max_length=None, unique=True)),
                ('registration_date', models.DateField()),
                ('address', models.TextField()),
                ('number_of_employees', models.IntegerField()),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_phone', companies.encryption.EncryptedCharField(max_length=None)),
                ('email_address', companies.encryption.EncryptedEmailField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
        ),
    ]
